"""add_compound_indexes

Revision ID: 571144909f61
Revises: e4f5a6b7c8d9
Create Date: 2026-08-09 23:50:58.428170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571144909f61'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_positions_user_asset', 'positions', ['user_id', 'asset_id'], unique=False, if_not_exists=True)
    op.create_index('idx_txs_user_pos', 'asset_transactions', ['user_id', 'position_id'], unique=False, if_not_exists=True)
    op.create_index('idx_txs_user_date_desc', 'asset_transactions', ['user_id', sa.text('transaction_date DESC')], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_txs_user_date_desc', table_name='asset_transactions', if_exists=True)
    op.drop_index('idx_txs_user_pos', table_name='asset_transactions', if_exists=True)
    op.drop_index('idx_positions_user_asset', table_name='positions', if_exists=True)
    # ### end Alembic commands ###
